### ISSUE TITLE
Raise an exception from the execute function of an action.

### ISSUE THREAD

**Issue by nicolasvandooren** [OsiriX-Foundation/karnak#73]
For the moment, it is not possible to throw an exception from the execute funtion of an ActionItem.
When an exception is thrown during the execution of an action, the de-identification should be stopped and not sent to the destination.
This exception can occur, when the action doesn't know what to do or when it risks corrupting the DICOM.

**Comment by nroduit** [comment]
Do you have an example in mind?

**Comment by nicolasvandooren** [comment]
The examples are inspired by the use of the DICOM standard
The first, which will normally never happen, is when the SOP UID is not set in the DICOM instance. When the action will be chosen (X/Z/D) and the SOP UID is not defined, the action should throw an exception.

The second one, it's if the user defined a Remove and the attribute is required for the current SOP. This will throw an exception that specifies that for this SOP UID that deletion cannot be performed.

**Comment by nroduit** [comment]
The first is not possible because SOP UID is used by the DICOM communication of the gateway. So this situation shouldn't exist. We have to define the minimal tags which are mandatory and check that at the beginning (if not throw an exception).

For the 2nd example, it may be necessary to prohibit the removal of  the minimal tags, perhaps by rechecking these tags at the end (if not throw an exception).

**Comment by nroduit** [comment]
If an exception is thrown, the strictest action is chosen, see #138
